--- 
 - name: using handlers
   hosts: all
   gather_facts: false
   become: yes
   tasks: 
    - name: installing httpd
      yum: 
       name: httpd
       state: present
      notify:
        - starting httpd
   handlers:
     - name: starting httpd
       service:
          name: httpd
          state: started
      #register: output
    #- debug: var=output.changed
    #- name: stopig vim
    #  service:
    #   name: httpd
    #   state: started
    #  when: output.changed == True

      ##else we can do by using handler variable